/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemController;

/**
 *
 * @author AshitaRaghu
 */
public class DietPepsi extends javax.swing.JPanel {
     private ItemController itemController;
    /**
     * Creates new form DietPepsi
     */
    public DietPepsi() {
        initComponents();
        itemController = new ItemController();
    }
    public void setPrice(double price){
        dietPepsiPriceTextField.setText(Double.toString(price));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dietPespiImageLabel = new javax.swing.JLabel();
        dietPepsiPriceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dietPepsiUpdateButton = new javax.swing.JButton();

        dietPespiImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dietPepsi.jpg"))); // NOI18N

        dietPepsiPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietPepsiPriceTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Price");

        dietPepsiUpdateButton.setText("update");
        dietPepsiUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietPepsiUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dietPespiImageLabel)
                .addGap(18, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dietPepsiPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dietPepsiUpdateButton))
                    .addComponent(jLabel9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dietPepsiPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dietPepsiUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dietPespiImageLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dietPepsiPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietPepsiPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietPepsiPriceTextFieldActionPerformed

    private void dietPepsiUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietPepsiUpdateButtonActionPerformed
        // TODO add your handling code here:
        double price = Double.valueOf(dietPepsiPriceTextField.getText());
        itemController.updatePrice(price,111);
    }//GEN-LAST:event_dietPepsiUpdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dietPepsiPriceTextField;
    private javax.swing.JButton dietPepsiUpdateButton;
    private javax.swing.JLabel dietPespiImageLabel;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
