/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemController;
import controller.UserLogController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import main.Main;

/**
 *
 * @author Sonam
 */
public class ManagerControlPanel extends javax.swing.JPanel {
    private ItemController itemController;
    private UserLogController userLogController;
    private AdminManagerUI adminManagerUI;
    /**
     * Creates new form ManagerControlPanel
     */
   public ManagerControlPanel() {
        initComponents();
        this.itemController = itemController = ItemController.getItemControllerInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statisticsPanel = new javax.swing.JPanel();
        BevSnacksStatisticsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        beveragesSoldTextField = new javax.swing.JTextField();
        snacksSoldTextField = new javax.swing.JTextField();
        bevSnackPieChartButton = new javax.swing.JButton();
        bevSnackBarChartButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        itemsPieChartButton = new javax.swing.JButton();
        itemsBarChartButton = new javax.swing.JButton();
        nutritionalStatisticsPanel = new javax.swing.JPanel();
        nutritionalStatisticsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        machine1RadioButton = new javax.swing.JRadioButton();
        allMachinesRadioButton = new javax.swing.JRadioButton();
        machine2RadioButton = new javax.swing.JRadioButton();
        addNewItemPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        proteinLabel = new javax.swing.JLabel();
        sugarsLabel = new javax.swing.JLabel();
        carbohydratesLabel = new javax.swing.JLabel();
        codeTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        proteinTextField = new javax.swing.JTextField();
        sugarsTextField = new javax.swing.JTextField();
        carbohydratesTextField = new javax.swing.JTextField();
        caloriesLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        machineIDLabel = new javax.swing.JLabel();
        caloriesTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        countTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        machineIDTextField = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        BevSnacksStatisticsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Number of Beverages Sold :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Number of Snacks Sold : ");

        beveragesSoldTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beveragesSoldTextFieldActionPerformed(evt);
            }
        });

        snacksSoldTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacksSoldTextFieldActionPerformed(evt);
            }
        });

        bevSnackPieChartButton.setText("Pie Chart");
        bevSnackPieChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bevSnackPieChartButtonActionPerformed(evt);
            }
        });

        bevSnackBarChartButton.setText("Bar Chart");
        bevSnackBarChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bevSnackBarChartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BevSnacksStatisticsPanelLayout = new javax.swing.GroupLayout(BevSnacksStatisticsPanel);
        BevSnacksStatisticsPanel.setLayout(BevSnacksStatisticsPanelLayout);
        BevSnacksStatisticsPanelLayout.setHorizontalGroup(
            BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BevSnacksStatisticsPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(beveragesSoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snacksSoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BevSnacksStatisticsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bevSnackPieChartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bevSnackBarChartButton)
                .addGap(132, 132, 132))
        );
        BevSnacksStatisticsPanelLayout.setVerticalGroup(
            BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BevSnacksStatisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(beveragesSoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(snacksSoldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BevSnacksStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bevSnackPieChartButton)
                    .addComponent(bevSnackBarChartButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("All items Statistics");

        itemsPieChartButton.setText("Pie Chart");
        itemsPieChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsPieChartButtonActionPerformed(evt);
            }
        });

        itemsBarChartButton.setText("Bar Chart");
        itemsBarChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsBarChartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(itemsPieChartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemsBarChartButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsPieChartButton)
                    .addComponent(itemsBarChartButton))
                .addContainerGap())
        );

        nutritionalStatisticsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nutritionalStatisticsButton.setText("Nutritional Statistics");
        nutritionalStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutritionalStatisticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nutritionalStatisticsPanelLayout = new javax.swing.GroupLayout(nutritionalStatisticsPanel);
        nutritionalStatisticsPanel.setLayout(nutritionalStatisticsPanelLayout);
        nutritionalStatisticsPanelLayout.setHorizontalGroup(
            nutritionalStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nutritionalStatisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutritionalStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        nutritionalStatisticsPanelLayout.setVerticalGroup(
            nutritionalStatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nutritionalStatisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutritionalStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Sales Satistics");

        machine1RadioButton.setText("Machine 1");
        machine1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine1RadioButtonActionPerformed(evt);
            }
        });

        allMachinesRadioButton.setText("All Machines");
        allMachinesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMachinesRadioButtonActionPerformed(evt);
            }
        });

        machine2RadioButton.setText("Machine 2");
        machine2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine2RadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(machine1RadioButton)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(machine2RadioButton)
                        .addGap(30, 30, 30)
                        .addComponent(allMachinesRadioButton))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allMachinesRadioButton)
                    .addComponent(machine2RadioButton)
                    .addComponent(machine1RadioButton))
                .addContainerGap())
        );

        addNewItemPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Add new item");

        codeLabel.setText("Code :");

        nameLabel.setText("Name :");

        proteinLabel.setText("Protein :");

        sugarsLabel.setText("Sugars :");

        carbohydratesLabel.setText("Carbohydrates: ");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        caloriesLabel.setText("Calories :");

        priceLabel.setText("Price :");

        countLabel.setText("Count :");

        categoryLabel.setText("Category :");

        machineIDLabel.setText("MachineID :");

        addItemButton.setText("Add");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewItemPanelLayout = new javax.swing.GroupLayout(addNewItemPanel);
        addNewItemPanel.setLayout(addNewItemPanelLayout);
        addNewItemPanelLayout.setHorizontalGroup(
            addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewItemPanelLayout.createSequentialGroup()
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewItemPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sugarsLabel)
                            .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(proteinLabel)
                                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLabel)
                                    .addComponent(codeLabel))))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(carbohydratesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewItemPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(addItemButton))
                    .addGroup(addNewItemPanelLayout.createSequentialGroup()
                        .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sugarsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carbohydratesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addComponent(caloriesLabel)
                            .addComponent(countLabel)
                            .addComponent(categoryLabel)
                            .addComponent(machineIDLabel))
                        .addGap(34, 34, 34)
                        .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caloriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machineIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(169, 169, 169))
        );
        addNewItemPanelLayout.setVerticalGroup(
            addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewItemPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caloriesLabel)
                        .addComponent(caloriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinLabel)
                    .addComponent(proteinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countLabel)
                    .addComponent(countTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sugarsLabel)
                    .addComponent(sugarsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carbohydratesLabel)
                    .addGroup(addNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carbohydratesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(machineIDLabel)
                        .addComponent(machineIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addItemButton))
        );

        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nutritionalStatisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logOutButton))
                    .addComponent(BevSnacksStatisticsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BevSnacksStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nutritionalStatisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void beveragesSoldTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beveragesSoldTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beveragesSoldTextFieldActionPerformed

    private void snacksSoldTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacksSoldTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snacksSoldTextFieldActionPerformed

    private void bevSnackPieChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bevSnackPieChartButtonActionPerformed
        // TODO add your handling code here:

        if(machine1RadioButton.isSelected()==false || machine2RadioButton.isSelected()==false || allMachinesRadioButton.isSelected()==false){
            JOptionPane.showMessageDialog(statisticsPanel,"Please select a machine");
        }
        int beveragesSold = Integer.parseInt(beveragesSoldTextField.getText());
        int snacksSold = Integer.parseInt(snacksSoldTextField.getText());
        double totalSale = beveragesSold+snacksSold;

        double beveragesFraction = (beveragesSold/totalSale)*100;
        double snacksFraction = (snacksSold/totalSale)*100;

        PieChart pieChart = new PieChart();
        pieChart.beverageVsSnackPieChart("Pie Chart","Beverages vs Snacks comparison",beveragesFraction,snacksFraction);
        pieChart.pack();
        pieChart.setVisible(true);
    }//GEN-LAST:event_bevSnackPieChartButtonActionPerformed

    private void bevSnackBarChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bevSnackBarChartButtonActionPerformed
        // TODO add your handling code here:
        if(machine1RadioButton.isSelected()==false || machine2RadioButton.isSelected()==false || allMachinesRadioButton.isSelected()==false){
            JOptionPane.showMessageDialog(statisticsPanel,"Please select a machine");
        }
        int beveragesSold = Integer.parseInt(beveragesSoldTextField.getText());
        int snacksSold = Integer.parseInt(snacksSoldTextField.getText());
        double totalSale = beveragesSold+snacksSold;

        double beveragesFraction = (beveragesSold/totalSale)*100;
        double snacksFraction = (snacksSold/totalSale)*100;

        BarChart barChart = new BarChart();
        barChart.beverageVsSnackBarChart("Bar Chart","Beverage vs Snack Comparison",beveragesFraction,snacksFraction);
        barChart.pack();
        barChart.setVisible(true);
    }//GEN-LAST:event_bevSnackBarChartButtonActionPerformed

    private void itemsPieChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsPieChartButtonActionPerformed
        // TODO add your handling code here:
        if(machine1RadioButton.isSelected()==false || machine2RadioButton.isSelected()==false || allMachinesRadioButton.isSelected()==false){
            JOptionPane.showMessageDialog(statisticsPanel,"Please select a machine");
        }
        ArrayList<Integer> itemsSoldCount = new ArrayList<Integer>();
        if(machine1RadioButton.isSelected())
        itemsSoldCount = itemController.getItemSoldCount("machine1");
        else if(machine1RadioButton.isSelected())
        itemsSoldCount = itemController.getItemSoldCount("machine2");
        else
        itemsSoldCount = itemController.getItemSoldCount("allMachines");

        PieChart pieChart = new PieChart();
        pieChart.itemSoldPieChart("Pie Chart","Items Sold Comparison",itemsSoldCount);
        pieChart.pack();
        pieChart.setVisible(true);
    }//GEN-LAST:event_itemsPieChartButtonActionPerformed

    private void itemsBarChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsBarChartButtonActionPerformed
        // TODO add your handling code here:
        if(machine1RadioButton.isSelected()==false || machine2RadioButton.isSelected()==false || allMachinesRadioButton.isSelected()==false){
            JOptionPane.showMessageDialog(statisticsPanel,"Please select a machine");
        }
        ArrayList<Integer> itemsSoldCount = new ArrayList<Integer>();
        if(machine1RadioButton.isSelected())
        itemsSoldCount = itemController.getItemSoldCount("machine1");
        else if(machine1RadioButton.isSelected())
        itemsSoldCount = itemController.getItemSoldCount("machine2");
        else
        itemsSoldCount = itemController.getItemSoldCount("allMachines");

        BarChart barChart = new BarChart();
        barChart.itemSoldBarChart("Bar Chart","Items Sold Comparison",itemsSoldCount);
        barChart.pack();
        barChart.setVisible(true);
    }//GEN-LAST:event_itemsBarChartButtonActionPerformed

    private void nutritionalStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutritionalStatisticsButtonActionPerformed
        // TODO add your handling code here:
        if(machine1RadioButton.isSelected()==false || machine2RadioButton.isSelected()==false || allMachinesRadioButton.isSelected()==false){
            JOptionPane.showMessageDialog(statisticsPanel,"Please select a machine");
        }
        int[] nutritionalItemsSoldCount = new int[100];
        if(machine1RadioButton.isSelected())
        nutritionalItemsSoldCount = itemController.getNutritionalItemSoldCount("machine1");
        else if(machine2RadioButton.isSelected())
        nutritionalItemsSoldCount = itemController.getNutritionalItemSoldCount("machine2");
        else
        nutritionalItemsSoldCount = itemController.getNutritionalItemSoldCount("allMachines");

        PieChart pieChart = new PieChart();
        pieChart.nutritionalItemsSoldPieChart("Pie Chart","Items Sold Comparison",nutritionalItemsSoldCount,itemController.getLowCalCount(),itemController.getLowCalNames(),itemController.getHighProteinCount(),itemController.getHighProteinNames(),itemController.getLowSugarsCount(),itemController.getLowSugarsNames());
        pieChart.pack();
        pieChart.setVisible(true);
    }//GEN-LAST:event_nutritionalStatisticsButtonActionPerformed

    private void machine1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine1RadioButtonActionPerformed
        // TODO add your handling code here:
        beveragesSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("beverage",4201)));
        snacksSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("snack",4201)));
    }//GEN-LAST:event_machine1RadioButtonActionPerformed

    private void allMachinesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMachinesRadioButtonActionPerformed
        // TODO add your handling code here:
        beveragesSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("beverage")));
        snacksSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("snack")));
    }//GEN-LAST:event_allMachinesRadioButtonActionPerformed

    private void machine2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine2RadioButtonActionPerformed
        // TODO add your handling code here:
        beveragesSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("beverage",4202)));
        snacksSoldTextField.setText(Integer.toString(itemController.getCategorySoldCount("snack",4202)));
    }//GEN-LAST:event_machine2RadioButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        String[] itemInfo = new String[12];
        itemInfo[0] = codeTextField.getText();
        itemInfo[1] = nameTextField.getText();
        itemInfo[2] = proteinTextField.getText();
        itemInfo[3] = sugarsTextField.getText();
        itemInfo[4] = carbohydratesTextField.getText();
        itemInfo[5] = caloriesTextField.getText();
        itemInfo[6] = priceTextField.getText();
        itemInfo[7] = countTextField.getText();
        itemInfo[8] = categoryTextField.getText();
        itemInfo[9] = machineIDTextField.getText();
        
        adminManagerUI.addNewItem(itemInfo);

        

        
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
    //    this.dispose();
       Main.getCardLayout().show(Main.getCards(),"Navigation");  
    }//GEN-LAST:event_logOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BevSnacksStatisticsPanel;
    private javax.swing.JButton addItemButton;
    private javax.swing.JPanel addNewItemPanel;
    private javax.swing.JRadioButton allMachinesRadioButton;
    private javax.swing.JButton bevSnackBarChartButton;
    private javax.swing.JButton bevSnackPieChartButton;
    private javax.swing.JTextField beveragesSoldTextField;
    private javax.swing.JLabel caloriesLabel;
    private javax.swing.JTextField caloriesTextField;
    private javax.swing.JLabel carbohydratesLabel;
    private javax.swing.JTextField carbohydratesTextField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField countTextField;
    private javax.swing.JButton itemsBarChartButton;
    private javax.swing.JButton itemsPieChartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JRadioButton machine1RadioButton;
    private javax.swing.JRadioButton machine2RadioButton;
    private javax.swing.JLabel machineIDLabel;
    private javax.swing.JTextField machineIDTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton nutritionalStatisticsButton;
    private javax.swing.JPanel nutritionalStatisticsPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JTextField proteinTextField;
    private javax.swing.JTextField snacksSoldTextField;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JLabel sugarsLabel;
    private javax.swing.JTextField sugarsTextField;
    // End of variables declaration//GEN-END:variables
}
