/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CartItemsController;
import controller.Observer;
import controller.PayCard;
import controller.PayCash;
import controller.PaymentContext;
import controller.SmartCardController;
import javax.swing.JOptionPane;

/**
 *
 * @author Sonam
 */
public class PaymentPanel extends javax.swing.JPanel implements Observer {

    private CustomerUI customerUI;
    private static CartItemsController cartItemsController;
    private SmartCardController smartCardController;
    private static PaymentContext context;
    private double price;
    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel(CustomerUI customerUI, CartItemsController cartItemsController) {
        initComponents();   
        this.customerUI = customerUI;
        this.cartItemsController = cartItemsController;
        smartCardController = new SmartCardController(customerUI);
        insertCoinPanel.setVisible(false);
        insertCardPanel.setVisible(false);
        cartItemsController.attachObserver(this);
    }
       
 /*   public void updatePrice(double price) {
        priceTextField.setValue(price);
    }*/
        
    @Override
    public void update(){
        priceTextField.setValue(cartItemsController.getTotalPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setPaymentPanel(){
       insertCoinPanel.setVisible(false);
       insertCardPanel.setVisible(false); 
       paymentButtonGroup.clearSelection();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentButtonGroup = new javax.swing.ButtonGroup();
        paymentPanel = new javax.swing.JPanel();
        insertCoinPanel = new javax.swing.JPanel();
        insertCoinLabel = new javax.swing.JLabel();
        insertNoteLabel = new javax.swing.JLabel();
        amoutPanel = new javax.swing.JPanel();
        cent10Button = new javax.swing.JButton();
        cent25Button = new javax.swing.JButton();
        cent50Button = new javax.swing.JButton();
        dollar1Button = new javax.swing.JButton();
        dollar5Button = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JFormattedTextField();
        cashRadioButton = new javax.swing.JRadioButton();
        cardRadioButton = new javax.swing.JRadioButton();
        buyCardPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        amoutTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cartNumber1TextField = new javax.swing.JTextField();
        reloadButton = new javax.swing.JButton();
        insertCardPanel = new javax.swing.JPanel();
        payCardButton = new javax.swing.JButton();
        insertCardMessageTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JTextField();
        buyCardPanel1 = new javax.swing.JPanel();
        buyCardLabel1 = new javax.swing.JLabel();
        dollar10Button1 = new javax.swing.JButton();
        dollar20Button1 = new javax.swing.JButton();
        dollar50Button1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cartNumber1TextField1 = new javax.swing.JTextField();
        checkBalanceButton = new javax.swing.JButton();

        insertCoinLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertCoin.jpg"))); // NOI18N

        insertNoteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertNote.png"))); // NOI18N

        cent10Button.setText("10c");
        cent10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cent10ButtonActionPerformed(evt);
            }
        });

        cent25Button.setText("25c");
        cent25Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cent25ButtonActionPerformed(evt);
            }
        });

        cent50Button.setText("50c");
        cent50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cent50ButtonActionPerformed(evt);
            }
        });

        dollar1Button.setText("$1");
        dollar1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar1ButtonActionPerformed(evt);
            }
        });

        dollar5Button.setText("$5");
        dollar5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar5ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout amoutPanelLayout = new javax.swing.GroupLayout(amoutPanel);
        amoutPanel.setLayout(amoutPanelLayout);
        amoutPanelLayout.setHorizontalGroup(
            amoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(amoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(amoutPanelLayout.createSequentialGroup()
                        .addComponent(cent10Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollar1Button))
                    .addGroup(amoutPanelLayout.createSequentialGroup()
                        .addComponent(cent25Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollar5Button))
                    .addComponent(cent50Button))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        amoutPanelLayout.setVerticalGroup(
            amoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amoutPanelLayout.createSequentialGroup()
                .addGroup(amoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cent10Button)
                    .addComponent(dollar1Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(amoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dollar5Button)
                    .addComponent(cent25Button, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cent50Button)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout insertCoinPanelLayout = new javax.swing.GroupLayout(insertCoinPanel);
        insertCoinPanel.setLayout(insertCoinPanelLayout);
        insertCoinPanelLayout.setHorizontalGroup(
            insertCoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCoinPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(insertCoinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(insertCoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertNoteLabel)))
        );
        insertCoinPanelLayout.setVerticalGroup(
            insertCoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCoinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertCoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertCoinPanelLayout.createSequentialGroup()
                        .addComponent(insertCoinLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(insertCoinPanelLayout.createSequentialGroup()
                        .addComponent(insertNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        priceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        priceLabel.setText("Total Price");

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        paymentButtonGroup.add(cashRadioButton);
        cashRadioButton.setText("Cash");
        cashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRadioButtonActionPerformed(evt);
            }
        });

        paymentButtonGroup.add(cardRadioButton);
        cardRadioButton.setText("Card");
        cardRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertCoinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashRadioButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardRadioButton)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRadioButton)
                    .addComponent(cardRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertCoinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Reload Smart Card");

        jLabel5.setText("Enter your card number:");

        jLabel9.setText("Enter amout to reload :");

        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buyCardPanelLayout = new javax.swing.GroupLayout(buyCardPanel);
        buyCardPanel.setLayout(buyCardPanelLayout);
        buyCardPanelLayout.setHorizontalGroup(
            buyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyCardPanelLayout.createSequentialGroup()
                .addGroup(buyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyCardPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(buyCardPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cartNumber1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(buyCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(amoutTextField)
                .addGap(21, 21, 21))
            .addGroup(buyCardPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(reloadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buyCardPanelLayout.setVerticalGroup(
            buyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyCardPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(buyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cartNumber1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buyCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reloadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        payCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertCard.png"))); // NOI18N
        payCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payCardButtonActionPerformed(evt);
            }
        });

        insertCardMessageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCardMessageTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Enter Card Number : ");

        cardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertCardPanelLayout = new javax.swing.GroupLayout(insertCardPanel);
        insertCardPanel.setLayout(insertCardPanelLayout);
        insertCardPanelLayout.setHorizontalGroup(
            insertCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertCardMessageTextField)
            .addGroup(insertCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(insertCardPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(payCardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertCardPanelLayout.setVerticalGroup(
            insertCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payCardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertCardMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buyCardLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card.jpg"))); // NOI18N

        dollar10Button1.setText("$10");
        dollar10Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar10Button1ActionPerformed(evt);
            }
        });

        dollar20Button1.setText("$20");
        dollar20Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar20Button1ActionPerformed(evt);
            }
        });

        dollar50Button1.setText("$50");
        dollar50Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollar50Button1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Buy SmartCal Card");

        jLabel7.setText("Enter your name :");

        javax.swing.GroupLayout buyCardPanel1Layout = new javax.swing.GroupLayout(buyCardPanel1);
        buyCardPanel1.setLayout(buyCardPanel1Layout);
        buyCardPanel1Layout.setHorizontalGroup(
            buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyCardPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyCardPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField1))
                    .addGroup(buyCardPanel1Layout.createSequentialGroup()
                        .addGroup(buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buyCardPanel1Layout.createSequentialGroup()
                                .addComponent(buyCardLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dollar50Button1)
                                    .addComponent(dollar20Button1)
                                    .addComponent(dollar10Button1)))
                            .addGroup(buyCardPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        buyCardPanel1Layout.setVerticalGroup(
            buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyCardPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buyCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyCardLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyCardPanel1Layout.createSequentialGroup()
                        .addComponent(dollar10Button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollar20Button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollar50Button1))))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Check Balance");

        jLabel11.setText("Enter your card number:");

        checkBalanceButton.setText("Check Balance");
        checkBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartNumber1TextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(checkBalanceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cartNumber1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(checkBalanceButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertCardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buyCardPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(buyCardPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buyCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardRadioButtonActionPerformed
        // TODO add your handling code here:
        context = new PaymentContext();
        context.setPaymentStrategy(new PayCard());

        insertCoinPanel.setVisible(false);
        insertCardPanel.setVisible(true);
    }//GEN-LAST:event_cardRadioButtonActionPerformed

    private void cashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRadioButtonActionPerformed
        // TODO add your handling code here:
        context = new PaymentContext();
        context.setPaymentStrategy(new PayCash());

        insertCardPanel.setVisible(false);
        insertCoinPanel.setVisible(true);
    }//GEN-LAST:event_cashRadioButtonActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
        if(priceTextField.getText()=="0.0"){
            customerUI.dispense();
        }
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void cardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTextFieldActionPerformed

    private void insertCardMessageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCardMessageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCardMessageTextFieldActionPerformed

    private void payCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payCardButtonActionPerformed
        // TODO add your handling code here:
        insertCardMessageTextField.setEditable(false);
        double price = Double.parseDouble(priceTextField.getText());
        double cardNumber = Double.parseDouble(cardNumberTextField.getText());
        System.out.println(cardNumber);
        if(cardNumber<300000 || cardNumber>400000){
            JOptionPane.showMessageDialog(paymentPanel,"Enter a valid card number");
        }
        double remainingBalance = context.pay(price,cardNumber);
        
        if(remainingBalance>=0)
        insertCardMessageTextField.setText("Your remaining balance is : "+Double.toString(remainingBalance));
        else
        insertCardMessageTextField.setText("Sorry! you do not have enough balance. Please reload your card");
    }//GEN-LAST:event_payCardButtonActionPerformed

    private void dollar5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar5ButtonActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(priceTextField.getText());
        double remainingPrice = context.pay(price, 5);
        if(remainingPrice>0)
        priceTextField.setText(Double.toString(remainingPrice));
        else if(remainingPrice>0){
            customerUI.giveChange("0.0");
        }
        else{
            priceTextField.setText("0");
            //    changeTextField.setText(Double.toString(Math.abs(remainingPrice)));
            customerUI.giveChange(Double.toString(Math.abs(remainingPrice)));
            customerUI.dispense();
        }
    }//GEN-LAST:event_dollar5ButtonActionPerformed

    private void dollar1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar1ButtonActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(priceTextField.getText());
        double remainingPrice = context.pay(price, 1);
        priceTextField.setText(Double.toString(remainingPrice));
        if(remainingPrice>0)
        priceTextField.setText(Double.toString(remainingPrice));
        else if(remainingPrice>0){
            customerUI.giveChange("0.0");
        }
        else{
            priceTextField.setText("0");
            //  changeTextField.setText(Double.toString(Math.abs(remainingPrice)));
            customerUI.giveChange(Double.toString(Math.abs(remainingPrice)));
            customerUI.dispense();
        }
    }//GEN-LAST:event_dollar1ButtonActionPerformed

    private void cent50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cent50ButtonActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(priceTextField.getText());
        double remainingPrice = context.pay(price, 0.50);
        priceTextField.setText(Double.toString(remainingPrice));
        if(remainingPrice>0)
        priceTextField.setText(Double.toString(remainingPrice));
        else if(remainingPrice>0){
            customerUI.giveChange("0.0");
        }
        else{
            priceTextField.setText("0");
            //  changeTextField.setText(Double.toString(Math.abs(remainingPrice)));
            customerUI.giveChange(Double.toString(Math.abs(remainingPrice)));
            customerUI.dispense();
        }
    }//GEN-LAST:event_cent50ButtonActionPerformed

    private void cent25ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cent25ButtonActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(priceTextField.getText());
        double remainingPrice = context.pay(price, 0.25);
        priceTextField.setText(Double.toString(remainingPrice));
        if(remainingPrice>0)
        priceTextField.setText(Double.toString(remainingPrice));
        else if(remainingPrice>0){
            customerUI.giveChange("0.0");
        }
        else{
            priceTextField.setText("0");
            //   changeTextField.setText(Double.toString(Math.abs(remainingPrice)));
            customerUI.giveChange(Double.toString(Math.abs(remainingPrice)));
            customerUI.dispense();
        }
    }//GEN-LAST:event_cent25ButtonActionPerformed

    private void cent10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cent10ButtonActionPerformed
        // TODO add your handling code here:
        price = Double.parseDouble(priceTextField.getText());
        double remainingPrice = context.pay(price, 0.10);
        priceTextField.setText(Double.toString(remainingPrice));
        if(remainingPrice>0){
            priceTextField.setText(Double.toString(remainingPrice));
        }
        else if(remainingPrice>0){
            customerUI.giveChange("0.0");
        }
        else{
            priceTextField.setText("0");
            //    changeTextField.setText(Double.toString(Math.abs(remainingPrice)));
            customerUI.giveChange(Double.toString(Math.abs(remainingPrice)));
            customerUI.dispense();
        }
    }//GEN-LAST:event_cent10ButtonActionPerformed

    private void dollar10Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar10Button1ActionPerformed
        // TODO add your handling code here:
        String name = cardNumberTextField.getText();
        Integer cardNumber = smartCardController.addNewCard(name, 10);
        JOptionPane.showMessageDialog(paymentPanel,"Your card number is "+cardNumber+". Your balance now is "+10);
    }//GEN-LAST:event_dollar10Button1ActionPerformed

    private void dollar20Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar20Button1ActionPerformed
        // TODO add your handling code here:
        String name = cardNumberTextField.getText();
        Integer cardNumber = smartCardController.addNewCard(name, 20);
        JOptionPane.showMessageDialog(paymentPanel,"Your card number is "+cardNumber+". Your balance now is "+20);
    }//GEN-LAST:event_dollar20Button1ActionPerformed

    private void dollar50Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollar50Button1ActionPerformed
        // TODO add your handling code here:
        String name = cardNumberTextField.getText();
        Integer cardNumber = smartCardController.addNewCard(name, 50);
        JOptionPane.showMessageDialog(paymentPanel,"Your card number is "+cardNumber+". Your balance now is "+50);
    }//GEN-LAST:event_dollar50Button1ActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        // TODO add your handling code here:
        int cardNumber = Integer.valueOf(cartNumber1TextField.getText());
        double amount = Integer.valueOf(amoutTextField.getText());
        double balance = smartCardController.reload(cardNumber,amount);
        JOptionPane.showMessageDialog(paymentPanel,"Your card has been reloaded. Your balance now is "+balance);
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void checkBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButtonActionPerformed
        // TODO add your handling code here:
        int cardNumber = Integer.valueOf(cartNumber1TextField1.getText());
        double balance = smartCardController.checkBalance(cardNumber);
        JOptionPane.showMessageDialog(paymentPanel,"Your balance is "+balance);
    }//GEN-LAST:event_checkBalanceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amoutPanel;
    private javax.swing.JTextField amoutTextField;
    private javax.swing.JLabel buyCardLabel1;
    private javax.swing.JPanel buyCardPanel;
    private javax.swing.JPanel buyCardPanel1;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JRadioButton cardRadioButton;
    private javax.swing.JTextField cartNumber1TextField;
    private javax.swing.JTextField cartNumber1TextField1;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JButton cent10Button;
    private javax.swing.JButton cent25Button;
    private javax.swing.JButton cent50Button;
    private javax.swing.JButton checkBalanceButton;
    private javax.swing.JButton dollar10Button1;
    private javax.swing.JButton dollar1Button;
    private javax.swing.JButton dollar20Button1;
    private javax.swing.JButton dollar50Button1;
    private javax.swing.JButton dollar5Button;
    private javax.swing.JTextField insertCardMessageTextField;
    private javax.swing.JPanel insertCardPanel;
    private javax.swing.JLabel insertCoinLabel;
    private javax.swing.JPanel insertCoinPanel;
    private javax.swing.JLabel insertNoteLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JButton payCardButton;
    private javax.swing.ButtonGroup paymentButtonGroup;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JFormattedTextField priceTextField;
    private javax.swing.JButton reloadButton;
    // End of variables declaration//GEN-END:variables
}
