/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CartItemsController;
import controller.Observable;
import controller.ItemController;
import controller.Observer;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author AshitaRaghu
 */
public class SnackPanel extends javax.swing.JPanel {

    private Integer machineID;
    private CustomerUI customerUI;
    private ItemController itemsController;
    private CartItemsController itemsCartController;
    ArrayList<Double> priceList;
    /**
     * Creates new form SnackPanel
     */
    public SnackPanel(CustomerUI customerUI, Integer machineID) {
        initComponents();
        this.machineID = machineID;
        this.customerUI = customerUI;
        itemsController = customerUI.getItemController();
        itemsCartController = customerUI.getItemsCartController();
        setCodeLabel();
        setPriceLabel();
        getCount();
    }
    
    public void changePrice(Integer index, Double value) {
        priceList.set(index-9, value); 
        setCodeLabel();
        setPriceLabel();
    }

    public void setCodeLabel(){
        
        ArrayList<Integer> codeList = itemsController.getCodeForMachine(machineID);
        
        granolaCodeLabel.setText(Integer.toString(codeList.get(9)));
        chipsCodeLabel.setText(Integer.toString(codeList.get(10)));
        nutsCodeLabel.setText(Integer.toString(codeList.get(11)));
        cookieCodeLabel.setText(Integer.toString(codeList.get(12)));
        driedFruitsCodeLabel.setText(Integer.toString(codeList.get(13)));
        popcornCodeLabel.setText(Integer.toString(codeList.get(14)));
        crackersCodeLabel.setText(Integer.toString(codeList.get(15)));
        veggieStrawsCodeLabel.setText(Integer.toString(codeList.get(16)));
        greekYogurtCodeLabel.setText(Integer.toString(codeList.get(17)));
        
        
    }
    public void setPriceLabel(){
    
        priceList = itemsController.getPriceForMachine(machineID);
        
        granolaPriceLabel.setText(Double.toString(priceList.get(0)));
        chipsPriceLabel.setText(Double.toString(priceList.get(1)));
        nutsPriceLabel.setText(Double.toString(priceList.get(2)));
        cookiePriceLabel.setText(Double.toString(priceList.get(3)));
        driedFruitsPriceLabel.setText(Double.toString(priceList.get(4)));
         popcornPriceLabel.setText(Double.toString(priceList.get(5)));
        crackersPriceLabel.setText(Double.toString(priceList.get(6)));
        veggieStrawsPriceLabel.setText(Double.toString(priceList.get(7)));
         greekYogurtPriceLabel.setText(Double.toString(priceList.get(8)));
    }
      public void getCount(){
        int[] count = itemsController.getCount(machineID);
        System.out.println(count[0]);
        if(count[0]==0)
            granolaPanel.setBackground(Color.red);
        if(count[1]==0)
            chipsPanel.setBackground(Color.red);
        if(count[2]==0)
            nutsPanel.setBackground(Color.red);
        if(count[3]==0)
            cookiePanel.setBackground(Color.red);
        if(count[4]==0)
            driedFruitPanel.setBackground(Color.red);
        if(count[5]==0)
            popcornPanel.setBackground(Color.red);
        if(count[6]==0)
            crackersPanel.setBackground(Color.red);
        if(count[7]==0)
            veggieStrawsPanel.setBackground(Color.red);
        if(count[8]==0)
            greekYogurtPanel.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        SnackPanel = new javax.swing.JPanel();
        nutsPanel = new javax.swing.JPanel();
        nutsButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nutsCodeLabel = new javax.swing.JLabel();
        nutsPriceLabel = new javax.swing.JLabel();
        granolaPanel = new javax.swing.JPanel();
        granolaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        granolaCodeLabel = new javax.swing.JLabel();
        granolaPriceLabel = new javax.swing.JLabel();
        chipsPanel = new javax.swing.JPanel();
        chipsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chipsCodeLabel = new javax.swing.JLabel();
        chipsPriceLabel = new javax.swing.JLabel();
        cookiePanel = new javax.swing.JPanel();
        cookieButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cookieCodeLabel = new javax.swing.JLabel();
        cookiePriceLabel = new javax.swing.JLabel();
        driedFruitPanel = new javax.swing.JPanel();
        driedFruitButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        driedFruitsCodeLabel = new javax.swing.JLabel();
        driedFruitsPriceLabel = new javax.swing.JLabel();
        popcornPanel = new javax.swing.JPanel();
        popcornButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        popcornCodeLabel = new javax.swing.JLabel();
        popcornPriceLabel = new javax.swing.JLabel();
        crackersPanel = new javax.swing.JPanel();
        crackersButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        crackersCodeLabel = new javax.swing.JLabel();
        crackersPriceLabel = new javax.swing.JLabel();
        veggieStrawsPanel = new javax.swing.JPanel();
        veggieStrawsButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        veggieStrawsCodeLabel = new javax.swing.JLabel();
        veggieStrawsPriceLabel = new javax.swing.JLabel();
        greekYogurtPanel = new javax.swing.JPanel();
        greekYogurtButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        greekYogurtCodeLabel = new javax.swing.JLabel();
        greekYogurtPriceLabel = new javax.swing.JLabel();

        nutsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuts.jpg"))); // NOI18N
        nutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Code :");

        jLabel10.setText("Price :");

        javax.swing.GroupLayout nutsPanelLayout = new javax.swing.GroupLayout(nutsPanel);
        nutsPanel.setLayout(nutsPanelLayout);
        nutsPanelLayout.setHorizontalGroup(
            nutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nutsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nutsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nutsCodeLabel))
                    .addGroup(nutsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nutsPriceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nutsPanelLayout.setVerticalGroup(
            nutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nutsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nutsCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nutsPriceLabel)))
        );

        granolaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/granola.jpg"))); // NOI18N
        granolaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                granolaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Code :");

        jLabel2.setText("Price :");

        javax.swing.GroupLayout granolaPanelLayout = new javax.swing.GroupLayout(granolaPanel);
        granolaPanel.setLayout(granolaPanelLayout);
        granolaPanelLayout.setHorizontalGroup(
            granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(granolaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(granolaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(granolaPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(granolaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(granolaPriceLabel))
                            .addGroup(granolaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(granolaCodeLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        granolaPanelLayout.setVerticalGroup(
            granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(granolaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(granolaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(granolaCodeLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(granolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(granolaPriceLabel))
                .addContainerGap())
        );

        chipsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chips.jpg"))); // NOI18N
        chipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipsButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Code :");

        jLabel6.setText("Price :");

        javax.swing.GroupLayout chipsPanelLayout = new javax.swing.GroupLayout(chipsPanel);
        chipsPanel.setLayout(chipsPanelLayout);
        chipsPanelLayout.setHorizontalGroup(
            chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chipsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chipsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chipsPriceLabel)
                            .addComponent(chipsCodeLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chipsPanelLayout.setVerticalGroup(
            chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chipsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chipsCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(chipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chipsPriceLabel))
                .addContainerGap())
        );

        cookieButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cookie.jpg"))); // NOI18N
        cookieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Code :");

        jLabel14.setText("Price :");

        javax.swing.GroupLayout cookiePanelLayout = new javax.swing.GroupLayout(cookiePanel);
        cookiePanel.setLayout(cookiePanelLayout);
        cookiePanelLayout.setHorizontalGroup(
            cookiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookiePanelLayout.createSequentialGroup()
                .addComponent(cookieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(cookiePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cookiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cookiePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cookieCodeLabel))
                    .addGroup(cookiePanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cookiePriceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cookiePanelLayout.setVerticalGroup(
            cookiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookiePanelLayout.createSequentialGroup()
                .addComponent(cookieButton)
                .addGap(18, 18, 18)
                .addGroup(cookiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cookieCodeLabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cookiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cookiePriceLabel)
                    .addComponent(jLabel14)))
        );

        driedFruitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/driedFruits.jpg"))); // NOI18N
        driedFruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driedFruitButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Code :");

        jLabel18.setText("Price :");

        javax.swing.GroupLayout driedFruitPanelLayout = new javax.swing.GroupLayout(driedFruitPanel);
        driedFruitPanel.setLayout(driedFruitPanelLayout);
        driedFruitPanelLayout.setHorizontalGroup(
            driedFruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driedFruitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driedFruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driedFruitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(driedFruitPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driedFruitsCodeLabel))
                    .addGroup(driedFruitPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driedFruitsPriceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        driedFruitPanelLayout.setVerticalGroup(
            driedFruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driedFruitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driedFruitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driedFruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(driedFruitsCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(driedFruitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(driedFruitsPriceLabel)))
        );

        popcornButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcorn.jpg"))); // NOI18N
        popcornButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popcornButtonActionPerformed(evt);
            }
        });

        jLabel21.setText("Code :");

        jLabel22.setText("Price :");

        javax.swing.GroupLayout popcornPanelLayout = new javax.swing.GroupLayout(popcornPanel);
        popcornPanel.setLayout(popcornPanelLayout);
        popcornPanelLayout.setHorizontalGroup(
            popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popcornPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popcornPanelLayout.createSequentialGroup()
                        .addGroup(popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(popcornPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(popcornPriceLabel))
                            .addGroup(popcornPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(popcornCodeLabel)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popcornPanelLayout.createSequentialGroup()
                        .addComponent(popcornButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        popcornPanelLayout.setVerticalGroup(
            popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popcornPanelLayout.createSequentialGroup()
                .addComponent(popcornButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(popcornCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(popcornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(popcornPriceLabel)))
        );

        crackersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crackers.jpg"))); // NOI18N
        crackersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crackersButtonActionPerformed(evt);
            }
        });

        jLabel25.setText("Code :");

        jLabel26.setText("Price :");

        javax.swing.GroupLayout crackersPanelLayout = new javax.swing.GroupLayout(crackersPanel);
        crackersPanel.setLayout(crackersPanelLayout);
        crackersPanelLayout.setHorizontalGroup(
            crackersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crackersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crackersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crackersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crackersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crackersCodeLabel))
                    .addGroup(crackersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crackersPriceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crackersPanelLayout.setVerticalGroup(
            crackersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crackersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crackersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crackersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(crackersCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crackersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(crackersPriceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        veggieStrawsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/veggieStraws.jpg"))); // NOI18N
        veggieStrawsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieStrawsButtonActionPerformed(evt);
            }
        });

        jLabel29.setText("Code :");

        jLabel30.setText("Price :");

        javax.swing.GroupLayout veggieStrawsPanelLayout = new javax.swing.GroupLayout(veggieStrawsPanel);
        veggieStrawsPanel.setLayout(veggieStrawsPanelLayout);
        veggieStrawsPanelLayout.setHorizontalGroup(
            veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veggieStrawsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veggieStrawsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(veggieStrawsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(veggieStrawsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veggieStrawsCodeLabel))
                            .addGroup(veggieStrawsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veggieStrawsPriceLabel)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        veggieStrawsPanelLayout.setVerticalGroup(
            veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veggieStrawsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veggieStrawsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(veggieStrawsCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(veggieStrawsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(veggieStrawsPriceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        greekYogurtButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greekYogurt.jpg"))); // NOI18N
        greekYogurtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greekYogurtButtonActionPerformed(evt);
            }
        });

        jLabel33.setText("Code :");

        jLabel34.setText("Price :");

        javax.swing.GroupLayout greekYogurtPanelLayout = new javax.swing.GroupLayout(greekYogurtPanel);
        greekYogurtPanel.setLayout(greekYogurtPanelLayout);
        greekYogurtPanelLayout.setHorizontalGroup(
            greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                .addGroup(greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(greekYogurtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greekYogurtPriceLabel))
                            .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greekYogurtCodeLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        greekYogurtPanelLayout.setVerticalGroup(
            greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greekYogurtPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(greekYogurtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(greekYogurtCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greekYogurtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(greekYogurtPriceLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout SnackPanelLayout = new javax.swing.GroupLayout(SnackPanel);
        SnackPanel.setLayout(SnackPanelLayout);
        SnackPanelLayout.setHorizontalGroup(
            SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SnackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SnackPanelLayout.createSequentialGroup()
                        .addComponent(crackersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(veggieStrawsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SnackPanelLayout.createSequentialGroup()
                        .addComponent(cookiePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(driedFruitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SnackPanelLayout.createSequentialGroup()
                        .addComponent(granolaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chipsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nutsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popcornPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greekYogurtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        SnackPanelLayout.setVerticalGroup(
            SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SnackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chipsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(granolaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cookiePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driedFruitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popcornPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SnackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SnackPanelLayout.createSequentialGroup()
                        .addComponent(greekYogurtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(veggieStrawsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crackersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(SnackPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void granolaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_granolaButtonActionPerformed
        itemsCartController.addItem(granolaCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 9, null);
    }//GEN-LAST:event_granolaButtonActionPerformed

    private void cookieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieButtonActionPerformed
        itemsCartController.addItem(cookieCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 12, null);
    }//GEN-LAST:event_cookieButtonActionPerformed

    private void veggieStrawsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieStrawsButtonActionPerformed
        itemsCartController.addItem(veggieStrawsCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 16, null);
    }//GEN-LAST:event_veggieStrawsButtonActionPerformed

    private void greekYogurtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greekYogurtButtonActionPerformed
        itemsCartController.addItem(greekYogurtCodeLabel.getText()); 
        customerUI.sendMessage("addtocart", 17, null);
    }//GEN-LAST:event_greekYogurtButtonActionPerformed

    private void nutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsButtonActionPerformed
        itemsCartController.addItem(nutsCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 11, null);
    }//GEN-LAST:event_nutsButtonActionPerformed

    private void driedFruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driedFruitButtonActionPerformed
        itemsCartController.addItem(driedFruitsCodeLabel.getText()); 
        customerUI.sendMessage("addtocart", 13, null);
    }//GEN-LAST:event_driedFruitButtonActionPerformed

    private void popcornButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popcornButtonActionPerformed
        itemsCartController.addItem(popcornCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 14, null);
    }//GEN-LAST:event_popcornButtonActionPerformed

    private void crackersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crackersButtonActionPerformed
        itemsCartController.addItem(crackersCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 15, null);
    }//GEN-LAST:event_crackersButtonActionPerformed

    private void chipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipsButtonActionPerformed
        itemsCartController.addItem(chipsCodeLabel.getText());  
        customerUI.sendMessage("addtocart", 10, null);
    }//GEN-LAST:event_chipsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SnackPanel;
    private javax.swing.JButton chipsButton;
    private javax.swing.JLabel chipsCodeLabel;
    private javax.swing.JPanel chipsPanel;
    private javax.swing.JLabel chipsPriceLabel;
    private javax.swing.JButton cookieButton;
    private javax.swing.JLabel cookieCodeLabel;
    private javax.swing.JPanel cookiePanel;
    private javax.swing.JLabel cookiePriceLabel;
    private javax.swing.JButton crackersButton;
    private javax.swing.JLabel crackersCodeLabel;
    private javax.swing.JPanel crackersPanel;
    private javax.swing.JLabel crackersPriceLabel;
    private javax.swing.JButton driedFruitButton;
    private javax.swing.JPanel driedFruitPanel;
    private javax.swing.JLabel driedFruitsCodeLabel;
    private javax.swing.JLabel driedFruitsPriceLabel;
    private javax.swing.JButton granolaButton;
    private javax.swing.JLabel granolaCodeLabel;
    private javax.swing.JPanel granolaPanel;
    private javax.swing.JLabel granolaPriceLabel;
    private javax.swing.JButton greekYogurtButton;
    private javax.swing.JLabel greekYogurtCodeLabel;
    private javax.swing.JPanel greekYogurtPanel;
    private javax.swing.JLabel greekYogurtPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nutsButton;
    private javax.swing.JLabel nutsCodeLabel;
    private javax.swing.JPanel nutsPanel;
    private javax.swing.JLabel nutsPriceLabel;
    private javax.swing.JButton popcornButton;
    private javax.swing.JLabel popcornCodeLabel;
    private javax.swing.JPanel popcornPanel;
    private javax.swing.JLabel popcornPriceLabel;
    private javax.swing.JButton veggieStrawsButton;
    private javax.swing.JLabel veggieStrawsCodeLabel;
    private javax.swing.JPanel veggieStrawsPanel;
    private javax.swing.JLabel veggieStrawsPriceLabel;
    // End of variables declaration//GEN-END:variables
}
